// Generated by gencpp from file age_pkg/Age.msg
// DO NOT EDIT!


#ifndef AGE_PKG_MESSAGE_AGE_H
#define AGE_PKG_MESSAGE_AGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace age_pkg
{
template <class ContainerAllocator>
struct Age_
{
  typedef Age_<ContainerAllocator> Type;

  Age_()
    : days(0)
    , months(0)
    , years(0)  {
    }
  Age_(const ContainerAllocator& _alloc)
    : days(0)
    , months(0)
    , years(0)  {
  (void)_alloc;
    }



   typedef int64_t _days_type;
  _days_type days;

   typedef int64_t _months_type;
  _months_type months;

   typedef int64_t _years_type;
  _years_type years;





  typedef boost::shared_ptr< ::age_pkg::Age_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::age_pkg::Age_<ContainerAllocator> const> ConstPtr;

}; // struct Age_

typedef ::age_pkg::Age_<std::allocator<void> > Age;

typedef boost::shared_ptr< ::age_pkg::Age > AgePtr;
typedef boost::shared_ptr< ::age_pkg::Age const> AgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::age_pkg::Age_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::age_pkg::Age_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::age_pkg::Age_<ContainerAllocator1> & lhs, const ::age_pkg::Age_<ContainerAllocator2> & rhs)
{
  return lhs.days == rhs.days &&
    lhs.months == rhs.months &&
    lhs.years == rhs.years;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::age_pkg::Age_<ContainerAllocator1> & lhs, const ::age_pkg::Age_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace age_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::age_pkg::Age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::age_pkg::Age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::age_pkg::Age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::age_pkg::Age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::age_pkg::Age_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::age_pkg::Age_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::age_pkg::Age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "247334725da2e1f19391c83b8669c57b";
  }

  static const char* value(const ::age_pkg::Age_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x247334725da2e1f1ULL;
  static const uint64_t static_value2 = 0x9391c83b8669c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::age_pkg::Age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "age_pkg/Age";
  }

  static const char* value(const ::age_pkg::Age_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::age_pkg::Age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 days\n"
"int64 months\n"
"int64 years\n"
;
  }

  static const char* value(const ::age_pkg::Age_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::age_pkg::Age_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.days);
      stream.next(m.months);
      stream.next(m.years);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Age_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::age_pkg::Age_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::age_pkg::Age_<ContainerAllocator>& v)
  {
    s << indent << "days: ";
    Printer<int64_t>::stream(s, indent + "  ", v.days);
    s << indent << "months: ";
    Printer<int64_t>::stream(s, indent + "  ", v.months);
    s << indent << "years: ";
    Printer<int64_t>::stream(s, indent + "  ", v.years);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGE_PKG_MESSAGE_AGE_H
