// Generated by gencpp from file count_words/CountWord.msg
// DO NOT EDIT!


#ifndef COUNT_WORDS_MESSAGE_COUNTWORD_H
#define COUNT_WORDS_MESSAGE_COUNTWORD_H

#include <ros/service_traits.h>


#include <count_words/CountWordRequest.h>
#include <count_words/CountWordResponse.h>


namespace count_words
{

struct CountWord
{

typedef CountWordRequest Request;
typedef CountWordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CountWord
} // namespace count_words


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::count_words::CountWord > {
  static const char* value()
  {
    return "52d808715c4d5b364d16952ee23dea9c";
  }

  static const char* value(const ::count_words::CountWord&) { return value(); }
};

template<>
struct DataType< ::count_words::CountWord > {
  static const char* value()
  {
    return "count_words/CountWord";
  }

  static const char* value(const ::count_words::CountWord&) { return value(); }
};


// service_traits::MD5Sum< ::count_words::CountWordRequest> should match
// service_traits::MD5Sum< ::count_words::CountWord >
template<>
struct MD5Sum< ::count_words::CountWordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::count_words::CountWord >::value();
  }
  static const char* value(const ::count_words::CountWordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::count_words::CountWordRequest> should match
// service_traits::DataType< ::count_words::CountWord >
template<>
struct DataType< ::count_words::CountWordRequest>
{
  static const char* value()
  {
    return DataType< ::count_words::CountWord >::value();
  }
  static const char* value(const ::count_words::CountWordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::count_words::CountWordResponse> should match
// service_traits::MD5Sum< ::count_words::CountWord >
template<>
struct MD5Sum< ::count_words::CountWordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::count_words::CountWord >::value();
  }
  static const char* value(const ::count_words::CountWordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::count_words::CountWordResponse> should match
// service_traits::DataType< ::count_words::CountWord >
template<>
struct DataType< ::count_words::CountWordResponse>
{
  static const char* value()
  {
    return DataType< ::count_words::CountWord >::value();
  }
  static const char* value(const ::count_words::CountWordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COUNT_WORDS_MESSAGE_COUNTWORD_H
