// Generated by gencpp from file sum_pkg/sum.msg
// DO NOT EDIT!


#ifndef SUM_PKG_MESSAGE_SUM_H
#define SUM_PKG_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <sum_pkg/sumRequest.h>
#include <sum_pkg/sumResponse.h>


namespace sum_pkg
{

struct sum
{

typedef sumRequest Request;
typedef sumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum
} // namespace sum_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sum_pkg::sum > {
  static const char* value()
  {
    return "645c2ebd161afbc4888fe6d5e4012e2f";
  }

  static const char* value(const ::sum_pkg::sum&) { return value(); }
};

template<>
struct DataType< ::sum_pkg::sum > {
  static const char* value()
  {
    return "sum_pkg/sum";
  }

  static const char* value(const ::sum_pkg::sum&) { return value(); }
};


// service_traits::MD5Sum< ::sum_pkg::sumRequest> should match
// service_traits::MD5Sum< ::sum_pkg::sum >
template<>
struct MD5Sum< ::sum_pkg::sumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sum_pkg::sum >::value();
  }
  static const char* value(const ::sum_pkg::sumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sum_pkg::sumRequest> should match
// service_traits::DataType< ::sum_pkg::sum >
template<>
struct DataType< ::sum_pkg::sumRequest>
{
  static const char* value()
  {
    return DataType< ::sum_pkg::sum >::value();
  }
  static const char* value(const ::sum_pkg::sumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sum_pkg::sumResponse> should match
// service_traits::MD5Sum< ::sum_pkg::sum >
template<>
struct MD5Sum< ::sum_pkg::sumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sum_pkg::sum >::value();
  }
  static const char* value(const ::sum_pkg::sumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sum_pkg::sumResponse> should match
// service_traits::DataType< ::sum_pkg::sum >
template<>
struct DataType< ::sum_pkg::sumResponse>
{
  static const char* value()
  {
    return DataType< ::sum_pkg::sum >::value();
  }
  static const char* value(const ::sum_pkg::sumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUM_PKG_MESSAGE_SUM_H
