// Generated by gencpp from file sum_pkg/sumRequest.msg
// DO NOT EDIT!


#ifndef SUM_PKG_MESSAGE_SUMREQUEST_H
#define SUM_PKG_MESSAGE_SUMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sum_pkg
{
template <class ContainerAllocator>
struct sumRequest_
{
  typedef sumRequest_<ContainerAllocator> Type;

  sumRequest_()
    : num1(0.0)
    , num2(0.0)  {
    }
  sumRequest_(const ContainerAllocator& _alloc)
    : num1(0.0)
    , num2(0.0)  {
  (void)_alloc;
    }



   typedef double _num1_type;
  _num1_type num1;

   typedef double _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::sum_pkg::sumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sum_pkg::sumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sumRequest_

typedef ::sum_pkg::sumRequest_<std::allocator<void> > sumRequest;

typedef boost::shared_ptr< ::sum_pkg::sumRequest > sumRequestPtr;
typedef boost::shared_ptr< ::sum_pkg::sumRequest const> sumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sum_pkg::sumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sum_pkg::sumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sum_pkg::sumRequest_<ContainerAllocator1> & lhs, const ::sum_pkg::sumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sum_pkg::sumRequest_<ContainerAllocator1> & lhs, const ::sum_pkg::sumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sum_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sum_pkg::sumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sum_pkg::sumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sum_pkg::sumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sum_pkg::sumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sum_pkg::sumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sum_pkg::sumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sum_pkg::sumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b40d33c58f42fc40e0db685f99189e91";
  }

  static const char* value(const ::sum_pkg::sumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb40d33c58f42fc40ULL;
  static const uint64_t static_value2 = 0xe0db685f99189e91ULL;
};

template<class ContainerAllocator>
struct DataType< ::sum_pkg::sumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sum_pkg/sumRequest";
  }

  static const char* value(const ::sum_pkg::sumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sum_pkg::sumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 num1\n"
"float64 num2\n"
"\n"
;
  }

  static const char* value(const ::sum_pkg::sumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sum_pkg::sumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sum_pkg::sumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sum_pkg::sumRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<double>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<double>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUM_PKG_MESSAGE_SUMREQUEST_H
