// Generated by gencpp from file sum_pkg/sumResponse.msg
// DO NOT EDIT!


#ifndef SUM_PKG_MESSAGE_SUMRESPONSE_H
#define SUM_PKG_MESSAGE_SUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sum_pkg
{
template <class ContainerAllocator>
struct sumResponse_
{
  typedef sumResponse_<ContainerAllocator> Type;

  sumResponse_()
    : sum(0.0)  {
    }
  sumResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef double _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::sum_pkg::sumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sum_pkg::sumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sumResponse_

typedef ::sum_pkg::sumResponse_<std::allocator<void> > sumResponse;

typedef boost::shared_ptr< ::sum_pkg::sumResponse > sumResponsePtr;
typedef boost::shared_ptr< ::sum_pkg::sumResponse const> sumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sum_pkg::sumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sum_pkg::sumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sum_pkg::sumResponse_<ContainerAllocator1> & lhs, const ::sum_pkg::sumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sum_pkg::sumResponse_<ContainerAllocator1> & lhs, const ::sum_pkg::sumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sum_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sum_pkg::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sum_pkg::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sum_pkg::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sum_pkg::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sum_pkg::sumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sum_pkg::sumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sum_pkg::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981739b4699a7cf1b15030371beffb96";
  }

  static const char* value(const ::sum_pkg::sumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981739b4699a7cf1ULL;
  static const uint64_t static_value2 = 0xb15030371beffb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::sum_pkg::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sum_pkg/sumResponse";
  }

  static const char* value(const ::sum_pkg::sumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sum_pkg::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sum\n"
;
  }

  static const char* value(const ::sum_pkg::sumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sum_pkg::sumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sum_pkg::sumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sum_pkg::sumResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<double>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUM_PKG_MESSAGE_SUMRESPONSE_H
