// Generated by gencpp from file count_words/CountWordResponse.msg
// DO NOT EDIT!


#ifndef COUNT_WORDS_MESSAGE_COUNTWORDRESPONSE_H
#define COUNT_WORDS_MESSAGE_COUNTWORDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace count_words
{
template <class ContainerAllocator>
struct CountWordResponse_
{
  typedef CountWordResponse_<ContainerAllocator> Type;

  CountWordResponse_()
    : count(0)  {
    }
  CountWordResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int16_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::count_words::CountWordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::count_words::CountWordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CountWordResponse_

typedef ::count_words::CountWordResponse_<std::allocator<void> > CountWordResponse;

typedef boost::shared_ptr< ::count_words::CountWordResponse > CountWordResponsePtr;
typedef boost::shared_ptr< ::count_words::CountWordResponse const> CountWordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::count_words::CountWordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::count_words::CountWordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::count_words::CountWordResponse_<ContainerAllocator1> & lhs, const ::count_words::CountWordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::count_words::CountWordResponse_<ContainerAllocator1> & lhs, const ::count_words::CountWordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace count_words

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::count_words::CountWordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::count_words::CountWordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count_words::CountWordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count_words::CountWordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count_words::CountWordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count_words::CountWordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::count_words::CountWordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32997d61b5b88168a021b6c972ff5bf1";
  }

  static const char* value(const ::count_words::CountWordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32997d61b5b88168ULL;
  static const uint64_t static_value2 = 0xa021b6c972ff5bf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::count_words::CountWordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "count_words/CountWordResponse";
  }

  static const char* value(const ::count_words::CountWordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::count_words::CountWordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 count\n"
;
  }

  static const char* value(const ::count_words::CountWordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::count_words::CountWordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountWordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::count_words::CountWordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::count_words::CountWordResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int16_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COUNT_WORDS_MESSAGE_COUNTWORDRESPONSE_H
